url: http://jdeboi.com
baseurl:

permalink: /projects/:year/:title:output_ext

# Site settings
title: jdeboi.com
email: jdeboi@gmail.com
description: Jenna deBoisblanc is a creative coder, teacher, and maker in New Orleans.

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: youtube
    url: https://www.youtube.com/channel/UCzaGufLNFoetara43evQhMg
  - title: instagram
    url: https://www.instagram.com/jdeboi/
  - title: github
    url: http://github.com/jdeboi
  - title: linkedin
    url: https://www.linkedin.com/in/jennadeboisblanc/

# Build settings
markdown: kramdown
